Tarea Distribuidos

In [80]:
import numpy as np
import pandas as pd

In [ ]:
vector = np.genfromtxt('./Archivos/KDDTrain.csv', delimiter=',', dtype=None)
print(vector[0])

In [81]:
vectorcito = pd.read_csv('./Archivos/KDDTrain.csv', delimiter=',')
vectorcito.head()

0  tcp ftp_data   SF  491   0.1  0.2  0.3  0.4  0.5  ...  0.17  0.03  \
0  0  udp    other   SF  146     0    0    0    0    0  ...  0.00  0.60   
1  0  tcp  private   S0    0     0    0    0    0    0  ...  0.10  0.05   
2  0  tcp     http   SF  232  8153    0    0    0    0  ...  1.00  0.00   
3  0  tcp     http   SF  199   420    0    0    0    0  ...  1.00  0.00   
4  0  tcp  private  REJ    0     0    0    0    0    0  ...  0.07  0.07   

   0.17.1  0.00.6  0.00.7  0.00.8  0.05  0.00.9   normal  20  
0    0.88    0.00    0.00    0.00   0.0    0.00   normal  15  
1    0.00    0.00    1.00    1.00   0.0    0.00  neptune  19  
2    0.03    0.04    0.03    0.01   0.0    0.01   normal  21  
3    0.00    0.00    0.00    0.00   0.0    0.00   normal  21  
4    0.00    0.00    0.00    0.00   1.0    1.00  neptune  21  

[5 rows x 43 columns]

In [82]:
file = open('./Archivos/KDDTrain.csv', 'r')
vector = []
for linea in file:
    vector.append((linea.strip()).split(','))
    ##print(vector)
file.close()

In [83]:
protocolos = []
servicios = []
flags = []
etiquetas = []
protocolo = []
servicio = []
flag = []
etiqueta = []
otros = []
for cosa in vector:
    protocolos.append(cosa[1])
    servicios.append(cosa[2])
    flags.append(cosa[3])
    etiquetas.append(cosa[41])
protocolo = np.unique(protocolos)
servicio = np.unique(servicios)
flag = np.unique(flags)
print(np.unique(protocolos))



['icmp' 'tcp' 'udp']


In [63]:
def one_hot(array):
    unique, inverse = np.unique(array, return_inverse=True)
    onehot = np.eye(unique.shape[0])[inverse]
    return onehot

print(one_hot(flags))

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
nuevoVector = []
for v in vector:
    v